# Generated by Django 5.1.1 on 2024-09-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('Loan_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Account_no', models.IntegerField()),
                ('Loan_amt', models.IntegerField()),
                ('Mobile_number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
